### ISSUE TITLE
loading bam with many contigs (~2^16) fails

### ISSUE THREAD

**Issue by timodonnell** [pyranges/bamread#10]
Contigs ids are represented as an int16, which fails for bams aligned to a large number of contigs (e.g. transcriptome alignments). This looks like an easy fix and I can submit a PR.

```
~/anaconda3/lib/python3.8/site-packages/bamread/read.py in read_bam_full(f, mapq, required_flag, filter_flag)
     26 def read_bam_full(f, mapq=0, required_flag=0, filter_flag=1540):
     27 
---> 28     chromosomes, starts, ends, strands, flags, chrmap, qstarts, qends, query_names, query_sequences, cigarstrings, query_qualities = _bamread_all(
     29         f, mapq, required_flag, filter_flag)
     30 

~/anaconda3/lib/python3.8/site-packages/bamread/src/bamread.pyx in bamread.src.bamread._bamread_all()

~/anaconda3/lib/python3.8/site-packages/bamread/src/bamread.pyx in bamread.src.bamread._bamread_all()

OverflowError: value too large to convert to int16_t

**Comment by catsargent** [comment]
As it has been over a year since this has been raised, and the suggested solution still hasn't been merged, is there any other way of getting around this? I had also changed the code in the relevant .pyx file but even after running `cython bamread.py` I still get the same error. Not sure what else I need to do?
